/**
 * Modelagem sugerida de abas (PASSO 5) — referência para evolução das planilhas
 * e perfis em sheet_profiles. O parser atual normaliza para tabela contínua.
 */
export const DOMAIN_TAB_MODELS = {
  paid_media: {
    label: "Mídia paga",
    suggestedFields: [
      "data",
      "ano",
      "mes",
      "shopping",
      "plataforma",
      "campanha",
      "objetivo",
      "investimento",
      "impressoes",
      "alcance",
      "cliques",
      "ctr",
      "cpc",
      "cpm",
      "sessoes",
      "conversoes",
      "cpa",
    ],
    mapsToDomains: ["analytics", "vendors", "social_media"] as const,
  },
  social_media: {
    label: "Social media",
    suggestedFields: [
      "data",
      "shopping",
      "plataforma",
      "seguidores",
      "crescimento",
      "alcance",
      "engajamento",
      "views",
      "conteudo_top",
      "insight",
    ],
    mapsToDomains: ["social_media"] as const,
  },
  crm: {
    label: "CRM",
    suggestedFields: [
      "data",
      "shopping",
      "disparos",
      "open_rate",
      "ctr",
      "conversoes",
      "receita",
      "insight",
    ],
    mapsToDomains: ["multi_app", "shopping"] as const,
  },
  influencers: {
    label: "Influenciadores",
    suggestedFields: [
      "data",
      "shopping",
      "influenciador",
      "categoria",
      "seguidores",
      "plataforma",
      "conteudo",
      "alcance",
      "engajamento",
      "views",
      "investimento",
      "resultado",
    ],
    mapsToDomains: ["influencers"] as const,
  },
  executive_insights: {
    label: "Insights executivos",
    suggestedFields: [
      "data",
      "shopping",
      "destaque_positivo",
      "ponto_atencao",
      "aprendizado",
      "proximos_passos",
    ],
    mapsToDomains: ["insights", "venue"] as const,
  },
} as const;
