import type { CanonicalField } from "./types";

/** Synonyms → canonical field (normalized lowercase, no accents) */
export const FIELD_SYNONYMS: Record<CanonicalField, string[]> = {
  customer_name: [
    "cliente",
    "nome_cliente",
    "customer",
    "customer_name",
    "empresa",
    "razao_social",
    "nome do cliente",
    "client",
    "buyer",
    "comprador",
  ],
  product_name: [
    "produto",
    "product",
    "product_name",
    "item",
    "descricao",
    "description",
    "nome_produto",
    "servico",
  ],
  category: [
    "categoria",
    "category",
    "segmento",
    "segment",
    "tipo",
    "grupo",
    "familia",
  ],
  amount: [
    "valor",
    "amount",
    "total",
    "receita",
    "revenue",
    "vendas",
    "sales",
    "preco",
    "price",
    "faturamento",
    "montante",
  ],
  quantity: [
    "quantidade",
    "qty",
    "quantity",
    "qtd",
    "units",
    "unidades",
    "volume",
  ],
  date: [
    "data",
    "date",
    "dt",
    "periodo",
    "period",
    "mes",
    "month",
    "ano",
    "year",
    "competencia",
  ],
  region: [
    "regiao",
    "region",
    "estado",
    "state",
    "cidade",
    "city",
    "pais",
    "country",
    "uf",
    "local",
  ],
  status: [
    "status",
    "situacao",
    "estado_pedido",
    "order_status",
    "fase",
  ],
  email: ["email", "e-mail", "correio", "mail"],
  phone: ["telefone", "phone", "celular", "mobile", "fone"],
  sku: ["sku", "codigo", "code", "id_produto", "product_id", "ref"],
  unknown: [],
};

export const CANONICAL_FIELDS = Object.keys(FIELD_SYNONYMS).filter(
  (k) => k !== "unknown"
) as CanonicalField[];
